---
# Jira role

- name: install Jira dependencies
  apt:
    pkg:
      - mysql-client

- name: Ensure commands can be executed as www-data - set shell
  user:
    name: www-data
    shell: /bin/false

- name: Copy jira init script
  copy:
    src: jira.service
    dest: /etc/systemd/system/jira.service
  notify:
    - restart jira

- name: enable jira
  systemd:
    name: jira
    enabled: yes
    daemon_reload: yes

- name: add backup pruner cron job
  cron:
    name: clean old Jira exports
    state: present
    job: find /var/www/jira/var/jira/export -maxdepth 1 -type f -mtime +150 -delete -regextype sed -regex '.*/[0-9]\{4\}-[A-Z][a-z]\{2\}-[0-9]\{2\}.*.zip'
    day: '*'
    minute: '0'
    hour: '0'

- name: add corrupted backup pruner cron job
  cron:
    name: clean old Jira corrupted exports
    state: present
    job: find /var/www/jira/var/jira/export/corrupted -maxdepth 1 -type f -mtime +150 -delete -regextype sed -regex '.*/[0-9]\{4\}-[A-Z][a-z]\{2\}-[0-9]\{2\}.*.zip'
    day: '*'
    minute: '0'
    hour: '0'
