---
- name: Set up the Discourse instances
  hosts: forum
  become: true
  roles:
    - role: common-server
      tags: 'common-server'

    - role: docker-compose
      tags: 'docker'

    - role: discourse
      tags: 'discourse'

    - role: nginx-proxy
      tags: nginx
      vars:
        NGINX_PROXY_CONFIG_PATH: /etc/nginx/sites-available/discourse
        NGINX_PROXY_INTERNAL_SCHEME: http
        NGINX_PROXY_INTERNAL_DOMAIN: unix
        NGINX_PROXY_INTERNAL_PORT: "/var/discourse/shared/standalone/nginx.http.sock:"
